config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'
 resources :items, except: [:index] do
   member do
     post 'complete'
   end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
"""
Author: Pranjali Pokharel
Item model validations for title and its methods
"""


class Item < ApplicationRecord
  validates_presence_of :title
  validate :past_due_date

  private
  def past_due_date
    # Throw error if the item due date is in the past
    if !due_date.blank? && due_date < Date.today
      self.errors.add(:due_date, "Due date cannot be in the past!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
"""
Author: Pranjali Pokharel
File contains the methods to make changes to our Item model
Methods to create new To-Do Item, edit existing Item, or destroy an Item are here
"""


class ItemsController < ApplicationController
  def new
    # Method takes to the new To-Do item view
    @item = Item.new
    render :'items/show_form'
  end

  def create
    # Method creates a new To-Do Item with form data
    @item = Item.new(item_params)
    save_item
  end

  def edit
    # Method allows the user to edit an existing To-Do item
    @item = Item.find(params[:id])
    render :'items/show_form'
  end

  def update
    # Method to update the edited item data
    @item = Item.find(params[:id])
    @item.assign_attributes(item_params)
    save_item
  end

  def complete
    # Method to complete the To-Do item
    @item = Item.find(params[:id])
    @item.completed= TRUE
    @item.completed_on= Date.today
    @item.save
    @items = Item.all
    render :'items/reload_items'
  end

  def destroy
    # Method allow the user to delete the To-Do item
    @item = Item.find(params[:id])
    @item.destroy
    @items = Item.all
    render :'items/reload_items'
  end

  private
  def save_item
    if @item.save
      @items = Item.all
      render :'items/hide_form'
    else
      render :'items/show_form'
    end
  end

  def item_params
    # Form parameters of the item model form
    params.require(:item).permit(:title, :description, :due_date)
  end
end

app/controllers/pages_controller.rb
"""
Controllers to manage our model Item
Author: Pranjali Pokharel
"""
class PagesController < ApplicationController

  def home
    """
    Home Page Controller displays and allows user to perform various operations on the Model
    "
    @items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_item_list.html.erb
<% if items.empty? %>
  <span class="text-warning">There are no To-Do items! Create one by using the button above</span>
<% else %>
  <table class="table table-hover table-responsive table-bordered">
    <thead><h3>To-Do Items</h3>
    <tr>
      <th>Complete</th>
      <th>Item</th>
      <th>Description</th>
      <th>Due Date</th>
      <th>Completed</th>
      <th>Completed On</th>
      <th>Created At</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% items.each do |item| -%>
      <tr>
        <td><%= link_to complete_item_path(item), remote: true, method: :post do %>
            <i class="glyphicon glyphicon-check"></i></td>
          <% end %>
        <td><strong><%= item.title %></strong></td>
        <td><%= item.description %></td>
        <% if item.completed %>
          <td class="text-success"><%= item.due_date %></td>
        <% elsif item.due_date && Date.today >= item.due_date %>
          <td class="text-danger"><b><%= item.due_date %></b></td>
        <% else %>
          <td><%= item.due_date %></td>
        <% end %>
        <td><%= item.completed %></td>
        <% if item.completed_on %>
          <td><%= item.completed_on.to_date.to_s %></td>
        <% else %>
          <td> -- </td>
        <% end %>
          <td><%= item.created_at.to_date.to_s %></td>
        <td><%= link_to edit_item_path(item), remote: true do %>
            <i class="glyphicon glyphicon-edit"></i></td>
          <% end %>
        <td><%= link_to item_path(item), remote: true, method: :delete, data: {confirm: "Delete To-Do item #{item.title}?"} do%>
            <i class="glyphicon glyphicon-remove"></i></td>
            <% end -%>
      </tr>
    <% end -%>
    </tbody>
  </table>
<% end -%>

app/views/items/_items_form.html.erb
<div class="modal-content">
  <div class="modal-header">
    <div class="modal-title"><%= item.new_record? ? 'Add New To-Do Item' : "Edit Item #{item.title}"%></div>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <%= simple_form_for item, defaults: { wrapper_html: {class: 'form-group'} }, class: 'clearfix', remote: true do |form|%>
    <%= form.input :title,
                   input_html: {class: 'form-control'}%>
    <%= form.input :description,
                   input_html: {class: 'form-control'}%>
    <%= form.input :due_date, label: 'Due Date',
                   label_html: {class: 'date-label'}%>
    <div class="modal-footer">
      <%= form.submit 'Add', class: 'btn btn-success'%>
    </div>
    <% end %>
  </div>
</div>

app/views/items/hide_form.js.erb
/*
Author: Pranjali Pokharel
Code to show the To Do items list after the creation form has been submitted
Redirect to show all To Do items via javascript rather than normal redirect_to method
*/
$('#item-list').html('<%= j(render partial: 'items/item_list', locals: {items: @items}) %>');
$('#modal').modal('hide');

app/views/items/reload_items.js.erb
/*
Author: Pranjali Pokharel
Code to show the refreshed To Do items list after an item has been deleted or marked as completed
Redirect to show all remaining To Do items via javascript rather than normal redirect_to method
*/
$('#item-list').html('<%= j(render partial: 'items/item_list', locals: {items: @items}) %>');

app/views/items/show_form.js.erb
/*
Author: Pranjali Pokharel
Code to show the create a new item modal
*/
m = $('#modal');
m.html('<%= j(render partial: 'items/items_form', locals: {item: @item})%>');
m.modal('show');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
      <div class="text-center">
        <h1>To-Do</h1>
        <p>Welcome to the To Do application! </p>
        <%= link_to 'Add To-Do Item', new_item_path, class:"btn btn-primary btn-lg", remote: true %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <div id="item-list" class="container">
      <%= render partial: 'items/item_list', locals: {items: @items} %>
    </div>
  </body>
</html>
<div id="modal" class="modal fade">
</div>